# - Try to find KSysguard
#  KSYSGUARDPROC_LIBRARIES - The libraries needed to use KSysgard proc
#  KSYSGUARDPROC_DEFINITIONS - Compiler switches required for using KSysguard
if(KSYSGUARDPROC_LIBRARIES AND KSYSGUARDPROC_LIBRARIES)
  # in cache already
  set(KSYSGUARDPROC_FOUND TRUE)
else(KSYSGUARDPROC_LIBRARIES AND KSYSGUARDPROC_LIBRARIES)
    find_path(KSYSGUARDPROC_INCLUDE_DIR ksysguard/processes.h
    PATH_SUFFIXES KF5
    )

    # message("INCLUDE ${KSYSGUARDPROC_INCLUDE_DIR} ${CMAKE_INCLUDE_PATH}/include/KF5")

    find_library(KSYSGUARDPROC_LIBRARY NAMES processcore)

    # message("LIBRARIES ${KSYSGUARDPROC_LIBRARY}")

    set(KSYSGUARDPROC_LIBRARIES ${KSYSGUARDPROC_LIBRARY} )
    set(KSYSGUARDPROC_INCLUDE_DIRS ${KSYSGUARDPROC_INCLUDE_DIR} )

    include(FindPackageHandleStandardArgs)

    find_package_handle_standard_args(KSysguardProc DEFAULT_MSG
    KSYSGUARDPROC_LIBRARY KSYSGUARDPROC_INCLUDE_DIR)

    mark_as_advanced(KSYSGUARDPROC_INCLUDE_DIR KSYSGUARDPROC_LIBRARY )
endif(KSYSGUARDPROC_LIBRARIES AND KSYSGUARDPROC_LIBRARIES)